import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { CookiesProvider } from 'next-client-cookies/server';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="pt-14 m-auto max-w-3xl px-4">
          <CookiesProvider>
            {children}
          </CookiesProvider>
        </div>
      </body>
    </html>
  );
}
